
pipeline {
    agent any 
    stages {
        stage('Install dependencies') { 
            steps {
                dir("ui"){
                    sh 'npm install'
                }
            }
        }
        stage('Test') { 
            steps {
                dir("ui"){
                    sh 'npm run ci-test'
                }
            }
        }
        stage('Production-Build') { 
            steps {
                dir("ui"){
                    sh 'npm run build'
                }
            }
        }
    }
}