
pipeline {
    agent any 
    stages {
        stage('Install dependencies') { 
            steps {
                dir("ui"){
                    sh 'npm install'
                }
            }
        }
        stage('Test') { 
            steps {
                dir("ui"){
                    // sh 'npm run ci-test'
                    sh 'echo TEST'
                }
            }
        }
        stage('Production-Build') { 
            steps {
                dir("ui"){
                    sh 'npm run build'
                }
            }
        }
    }
    post {
        always {
            emailext body: 'Jenkisn build status', subject: 'TEST', to: 'nagcloudlab@gmail.com'
        }
    }
}