
pipeline {
    agent any 
    stages {
        stage('Test') { 
            steps {
                sh 'echo Test'
            }
        }
        stage('Production-Build') { 
            steps {
                 sh 'echo Production-Build'
            }
        }
    }
}